name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: install dependencies
      run: apt-get install xorg-dev libglu1-mesa-dev
    
    - name: run cmake
      uses: lukka/run-cmake@v2
      with:
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ runner.workspace }}/build/'
