name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            name: windows
            generator: VS16Win64 
          - os: ubuntu-latest
            name: ubuntu
            generator: Ninja
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: copy binary 1
      if: contains( matrix.os, 'windows')
      run: "mkdir build && touch hello"  
        
    - name: copy binary 2
      if: contains( matrix.os, 'windows')
      run: "cp hello build"
        
    - name: install ubuntu opengl dependencies
      if: contains( matrix.os, 'ubuntu')
      run: sudo apt-get install xorg-dev libglu1-mesa-dev
    
    - name: run cmake
      uses: lukka/run-cmake@v2
      with:
        buildDirectory: build
        cmakeBuildType: Release
        cmakeGenerator: ${{ matrix.generator }}
        
    - name: copy binary
      if: contains( matrix.os, 'windows')
      run: "cp build/Release/ogro_invasion.exe build 2>/dev/null || :"
  
    - name: release orgo invasion
      uses: actions/upload-artifact@v2
      with:
        run: "cp build/Release/ogro_invasion.exe build 2>/dev/null || :"
        name: ogro_invasion_${{ matrix.name }}
        path: |
          build/chapter_13/ogro_invasion/data
          build/chapter_13/ogro_invasion/ogro_invasion*
